---
title: "Logistic Regression Assignment"
output:
      html_document:
        keep_md: true
---

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pastecs)
library(knitr)
```

# Logistic Regression Assignment

## General instructions

You must submit the following. 

**Stata**

* Stata Log File
* Stata Do File
* Report in Word doc form with tables/figures cut and pasted from Stata output file

**R**

* RMarkdown file
* Knit report in HTML or PDF

## Part 1 - Statistical Model Building

You are interested in examining the association between the occurrence of major depression at any point during the life of the participant `DIS_DEP_EVER` and physical activity `PA_TOTAL_SHORT`. It is well known that there are many factors associated with depression [https://doi.org/10.1176/appi.ajp.2020.19111158](https://doi.org/10.1176/appi.ajp.2020.19111158). There also been attempts to develop data driven DAGs for depression as it is such an outcome with a very complicated causal web [https://doi.org/10.3389/fpsyt.2022.809745](https://doi.org/10.3389/fpsyt.2022.809745).

Your task in this analysis is to determine which variables should be included in a regression model examining the association between depression and physical activity. 

1. Identify the primary outcome of interest and the main predictor(s) of interest

2. Draw a causal diagram for your full causal model

3. Assess potential confounding variables on the relationship between the outcome and exposure of interest using two approaches we learned in class:  

    * A DAG/theory based approach
    * A data driven/model fit approach  
    
4. Conduct cross-tabulations of the outcome variable with categorical predictors.

    * Are you concerned about any of the cell sizes?  

5. Identify and fit the best model evaluating the association between your exposure and outcome of interest. Describe why you included/excluded predictors and how you compared between models to arrive at your final model.  

    * Insert your model output below. 
    * Interpret each of the coefficients and odds ratios.   

6. Evaluate the model and indicate if there are any issues with the reliability of the model, and if the model meets the assumptions of logistic regression. Use regression diagnostics. 

## Part 2 - Format and Effort 

### General Formatting
- A combination sentences/paragraphs with some bullet points is appropriate.
- Include a list of references where appropriate. For this assignment, you do not need to worry
about providing references to the scales/items within the dataset.

### Overall
- Assignments will be evaluated based on the overall effort and thoroughness of the assignment, attention to details, and overall presentation of results.

## Data

We will again be using the CanPath data. For this assignment you have access to the entire CanPath dataset. Your key variables of interest are

1. Outcome (__Hint. You will need to recode this variable__)
    * Occurrence of major depression at any point during the life of the participant
    * Variable name - `DIS_DEP_EVER`
2. Exposure (__Hint. In the data wrangling assignment we recoded this variable into 3 categories__)
    * Quantitative indicator of global physical activity in metabolic equivalent (MET)-minutes per week (IPAQ short form)
    * Variable name - `PA_TOTAL_SHORT`
